# Task Schema Definition
# claude-symphony Task Management Schema (Issue #4, #6, #8, #16 Resolution)

schema:
  name: "Project Tasks"
  version: "1.0.0"

# Required field definitions
fields:
  # Task name (Title)
  - name: "Task Name"
    type: "title"
    required: true
    description: "Task title"

  # Status field (Issue #16: Status field required!)
  - name: "Status"
    type: "select"
    required: true
    default: "To Do"
    options:
      - name: "To Do"
        color: "gray"
      - name: "In Progress"
        color: "blue"
      - name: "Review"
        color: "yellow"
      - name: "Done"
        color: "green"
      - name: "Blocked"
        color: "red"

  # Priority
  - name: "Priority"
    type: "select"
    required: false
    default: "Medium"
    options:
      - name: "High"
        color: "red"
      - name: "Medium"
        color: "yellow"
      - name: "Low"
        color: "green"

  # Order for sorting (Issue #5, #6, #8 resolution)
  - name: "Order"
    type: "number"
    required: true
    description: "Task order (for sorting)"
    auto_increment: true

  # Sprint
  - name: "Sprint"
    type: "select"
    required: false
    options:
      - name: "Sprint 1"
      - name: "Sprint 2"
      - name: "Sprint 3"

  # Assignee
  - name: "Assignee"
    type: "text"
    required: false

  # Estimated time
  - name: "Estimate"
    type: "text"
    required: false
    description: "Estimated time (e.g., 2h, 1d)"

  # Due date
  - name: "Due Date"
    type: "date"
    required: false

  # Dependencies
  - name: "Depends On"
    type: "text"
    required: false
    description: "Prerequisite task IDs (comma-separated)"

  # Stage
  - name: "Stage"
    type: "select"
    required: false
    options:
      - name: "06-implementation"
      - name: "07-refactoring"
      - name: "08-qa"
      - name: "09-testing"

# Task creation rules (Issue #6, #8 resolution: Sequential creation!)
creation_rules:
  # Parallel creation prohibited - order guarantee
  mode: "sequential"
  batch_size: 1

  # Sequential creation procedure
  procedure:
    - step: 1
      action: "create_single_task"
      description: "Create single task"
    - step: 2
      action: "verify_order_field"
      description: "Verify Order field"
    - step: 3
      action: "create_next_task"
      description: "Create next task (Order + 1)"

  # Prohibited actions
  prohibited:
    - "batch_create"      # Batch creation prohibited
    - "parallel_create"   # Parallel creation prohibited

  # Recommended actions
  recommended:
    - "explicit_order"    # Explicit Order value specification
    - "status_to_do"      # Create with Status = "To Do"
    - "sequential_naming" # Sequential naming

# Notion database creation template
notion_template:
  database_name: "{{PROJECT_NAME}} Tasks"

  properties:
    - "Task Name"    # title
    - "Status"       # select (required!)
    - "Priority"     # select
    - "Order"        # number (for sorting!)
    - "Sprint"       # select
    - "Assignee"     # text
    - "Estimate"     # text
    - "Due Date"     # date
    - "Depends On"   # text
    - "Stage"        # select

  # Default view settings
  views:
    - name: "Board View"
      type: "board"
      group_by: "Status"

    - name: "List View"
      type: "table"
      sort_by: "Order"
      sort_direction: "ascending"

    - name: "Sprint View"
      type: "board"
      group_by: "Sprint"
      filter:
        - "Status != Done"
